"""create child cateogries

Revision ID: 22a2e371f72a
Revises: 22e1d70e8873
Create Date: 2020-07-28 10:15:47.987906

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '22a2e371f72a'
down_revision = '22e1d70e8873'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sub_categories',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('tags', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('category_id', postgresql.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_sub_categories_created_at'), 'sub_categories', ['created_at'], unique=False)
    op.create_index(op.f('ix_sub_categories_description'), 'sub_categories', ['description'], unique=False)
    op.create_index(op.f('ix_sub_categories_name'), 'sub_categories', ['name'], unique=True)
    op.create_index(op.f('ix_sub_categories_tags'), 'sub_categories', ['tags'], unique=False)
    op.create_index(op.f('ix_sub_categories_updated_at'), 'sub_categories', ['updated_at'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sub_categories_updated_at'), table_name='sub_categories')
    op.drop_index(op.f('ix_sub_categories_tags'), table_name='sub_categories')
    op.drop_index(op.f('ix_sub_categories_name'), table_name='sub_categories')
    op.drop_index(op.f('ix_sub_categories_description'), table_name='sub_categories')
    op.drop_index(op.f('ix_sub_categories_created_at'), table_name='sub_categories')
    op.drop_table('sub_categories')
    # ### end Alembic commands ###
