"""refactor category model

Revision ID: 22e1d70e8873
Revises: 40640a4a84bf
Create Date: 2020-07-28 09:46:23.679096

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22e1d70e8873'
down_revision = '40640a4a84bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_categories_description', table_name='categories')
    op.drop_index('ix_categories_extra', table_name='categories')
    op.drop_column('categories', 'extra')
    op.drop_column('categories', 'description')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('description', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('categories', sa.Column('extra', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.create_index('ix_categories_extra', 'categories', ['extra'], unique=False)
    op.create_index('ix_categories_description', 'categories', ['description'], unique=False)
    # ### end Alembic commands ###
