"""update category set title field unique

Revision ID: 40640a4a84bf
Revises: 9e942d4843d2
Create Date: 2020-07-28 00:41:52.928411

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40640a4a84bf'
down_revision = '9e942d4843d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_categories_updated_at'), 'categories', ['updated_at'], unique=False)
    op.drop_index('ix_categories_title', table_name='categories')
    op.create_index(op.f('ix_categories_title'), 'categories', ['title'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_categories_title'), table_name='categories')
    op.create_index('ix_categories_title', 'categories', ['title'], unique=False)
    op.drop_index(op.f('ix_categories_updated_at'), table_name='categories')
    # ### end Alembic commands ###
