"""refactor mode SubCategories

Revision ID: 4abff45e61f9
Revises: db1aa557ba38
Create Date: 2020-07-28 17:39:01.690532

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4abff45e61f9'
down_revision = 'db1aa557ba38'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_sub_categories_created_at', table_name='sub_categories')
    op.drop_index('ix_sub_categories_updated_at', table_name='sub_categories')
    op.create_unique_constraint(None, 'sub_categories', ['id'])
    op.drop_column('sub_categories', 'updated_at')
    op.drop_column('sub_categories', 'created_at')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sub_categories', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('sub_categories', sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'sub_categories', type_='unique')
    op.create_index('ix_sub_categories_updated_at', 'sub_categories', ['updated_at'], unique=False)
    op.create_index('ix_sub_categories_created_at', 'sub_categories', ['created_at'], unique=False)
    # ### end Alembic commands ###
