"""drop sub categories model

Revision ID: 4acccd7899d1
Revises: 80cb27b9b0fc
Create Date: 2020-07-28 13:19:59.240516

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4acccd7899d1'
down_revision = '80cb27b9b0fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_sub_categories_created_at', table_name='sub_categories')
    op.drop_index('ix_sub_categories_description', table_name='sub_categories')
    op.drop_index('ix_sub_categories_name', table_name='sub_categories')
    op.drop_index('ix_sub_categories_tags', table_name='sub_categories')
    op.drop_index('ix_sub_categories_updated_at', table_name='sub_categories')
    op.drop_table('sub_categories')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sub_categories',
    sa.Column('id', postgresql.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('tags', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True),
    sa.Column('category_id', postgresql.UUID(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name='sub_categories_category_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='sub_categories_pkey'),
    sa.UniqueConstraint('id', name='sub_categories_id_key')
    )
    op.create_index('ix_sub_categories_updated_at', 'sub_categories', ['updated_at'], unique=False)
    op.create_index('ix_sub_categories_tags', 'sub_categories', ['tags'], unique=False)
    op.create_index('ix_sub_categories_name', 'sub_categories', ['name'], unique=True)
    op.create_index('ix_sub_categories_description', 'sub_categories', ['description'], unique=False)
    op.create_index('ix_sub_categories_created_at', 'sub_categories', ['created_at'], unique=False)
    # ### end Alembic commands ###
