"""refactor foreignkey relationship

Revision ID: 80cb27b9b0fc
Revises: 22a2e371f72a
Create Date: 2020-07-28 10:17:36.209087

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80cb27b9b0fc'
down_revision = '22a2e371f72a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'sub_categories', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sub_categories', type_='unique')
    # ### end Alembic commands ###
